### ISSUE TITLE
templates/section.html missing

### ISSUE THREAD

**Issue by devurandom** [getzola/hyde#24]
I create `content/blog/_index.md` and run `zola serve`. When browsing http://127.0.0.1:1111/blog/ I see:

> Welcome to Zola!
> 
> You're seeing this page because we couldn't find a template to render.
> 
> To modify this page, create a section.html file in the templates directory or install a theme.
> You can find what variables are available in this template in the documentation.

Using zola 0.10.1 with zola-hyde 27d885fbd95934bf2c65f73cf03899e4ac5cc4d1.

**Comment by Keats** [comment]
The template by default is a single section: the homepage. If you want additional sections, you can extend it.
