### ISSUE TITLE
Demo website isn't rendering correctly on Google Chrome

### ISSUE THREAD

**Issue by saket** [getzola/hyde#26]
Hey, not sure if you've already noticed but your demo website isn't rendering correctly on Google Chrome. I wasn't able to reproduce this on Safari.

![image](https://user-images.githubusercontent.com/2387680/116612387-7b177e80-a905-11eb-8391-65e9855c50bc.png)

**Comment by Keats** [comment]
Looks like netlify returns a 301 for the assets pointing to a non https location... 🤔
